# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dependencies.rpc_pb2 as rpc__pb2


class RpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeDataStream = channel.unary_stream(
                '/rpc.RpcService/SubscribeDataStream',
                request_serializer=rpc__pb2.SubscribeDataRequest.SerializeToString,
                response_deserializer=rpc__pb2.RealTimeData.FromString,
                )


class RpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeDataStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeDataStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeDataStream,
                    request_deserializer=rpc__pb2.SubscribeDataRequest.FromString,
                    response_serializer=rpc__pb2.RealTimeData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.RpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeDataStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rpc.RpcService/SubscribeDataStream',
            rpc__pb2.SubscribeDataRequest.SerializeToString,
            rpc__pb2.RealTimeData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
