# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=b'Z-github.com/SSSOC-CAN/nginx_issue/goserver/rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trpc.proto\x12\x03rpc\"\x16\n\x14SubscribeDataRequest\"(\n\tDataField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\xae\x01\n\x0cRealTimeData\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x13\n\x0bis_scanning\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12)\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1b.rpc.RealTimeData.DataEntry\x1a;\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.rpc.DataField:\x02\x38\x01\x32S\n\nRpcService\x12\x45\n\x13SubscribeDataStream\x12\x19.rpc.SubscribeDataRequest\x1a\x11.rpc.RealTimeData0\x01\x42/Z-github.com/SSSOC-CAN/nginx_issue/goserver/rpcb\x06proto3'
)




_SUBSCRIBEDATAREQUEST = _descriptor.Descriptor(
  name='SubscribeDataRequest',
  full_name='rpc.SubscribeDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)


_DATAFIELD = _descriptor.Descriptor(
  name='DataField',
  full_name='rpc.DataField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc.DataField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc.DataField.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=82,
)


_REALTIMEDATA_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='rpc.RealTimeData.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc.RealTimeData.DataEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc.RealTimeData.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=259,
)

_REALTIMEDATA = _descriptor.Descriptor(
  name='RealTimeData',
  full_name='rpc.RealTimeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='rpc.RealTimeData.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_scanning', full_name='rpc.RealTimeData.is_scanning', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rpc.RealTimeData.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rpc.RealTimeData.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REALTIMEDATA_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=259,
)

_REALTIMEDATA_DATAENTRY.fields_by_name['value'].message_type = _DATAFIELD
_REALTIMEDATA_DATAENTRY.containing_type = _REALTIMEDATA
_REALTIMEDATA.fields_by_name['data'].message_type = _REALTIMEDATA_DATAENTRY
DESCRIPTOR.message_types_by_name['SubscribeDataRequest'] = _SUBSCRIBEDATAREQUEST
DESCRIPTOR.message_types_by_name['DataField'] = _DATAFIELD
DESCRIPTOR.message_types_by_name['RealTimeData'] = _REALTIMEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeDataRequest = _reflection.GeneratedProtocolMessageType('SubscribeDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEDATAREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SubscribeDataRequest)
  })
_sym_db.RegisterMessage(SubscribeDataRequest)

DataField = _reflection.GeneratedProtocolMessageType('DataField', (_message.Message,), {
  'DESCRIPTOR' : _DATAFIELD,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.DataField)
  })
_sym_db.RegisterMessage(DataField)

RealTimeData = _reflection.GeneratedProtocolMessageType('RealTimeData', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _REALTIMEDATA_DATAENTRY,
    '__module__' : 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:rpc.RealTimeData.DataEntry)
    })
  ,
  'DESCRIPTOR' : _REALTIMEDATA,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RealTimeData)
  })
_sym_db.RegisterMessage(RealTimeData)
_sym_db.RegisterMessage(RealTimeData.DataEntry)


DESCRIPTOR._options = None
_REALTIMEDATA_DATAENTRY._options = None

_RPCSERVICE = _descriptor.ServiceDescriptor(
  name='RpcService',
  full_name='rpc.RpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=344,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeDataStream',
    full_name='rpc.RpcService.SubscribeDataStream',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEDATAREQUEST,
    output_type=_REALTIMEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPCSERVICE)

DESCRIPTOR.services_by_name['RpcService'] = _RPCSERVICE

# @@protoc_insertion_point(module_scope)
